/*
 * This file is generated by jOOQ.
 */
package com.avasiliuk.testtask.model.jooq.tables.records;


import com.avasiliuk.testtask.model.jooq.tables.OrderedProducts;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class OrderedProductsRecord extends UpdatableRecordImpl<OrderedProductsRecord> implements Record3<UUID, UUID, BigDecimal> {

    private static final long serialVersionUID = -193330342;

    /**
     * Create a detached OrderedProductsRecord
     */
    public OrderedProductsRecord() {
        super(OrderedProducts.ORDERED_PRODUCTS);
    }

    /**
     * Create a detached, initialised OrderedProductsRecord
     */
    public OrderedProductsRecord(UUID orderId, UUID productId, BigDecimal orderedPrice) {
        super(OrderedProducts.ORDERED_PRODUCTS);

        set(0, orderId);
        set(1, productId);
        set(2, orderedPrice);
    }

    /**
     * Getter for <code>PUBLIC.ORDERED_PRODUCTS.ORDER_ID</code>.
     */
    public UUID getOrderId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ORDERED_PRODUCTS.ORDER_ID</code>.
     */
    public void setOrderId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERED_PRODUCTS.PRODUCT_ID</code>.
     */
    public UUID getProductId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ORDERED_PRODUCTS.PRODUCT_ID</code>.
     */
    public void setProductId(UUID value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>PUBLIC.ORDERED_PRODUCTS.ORDERED_PRICE</code>.
     */
    public BigDecimal getOrderedPrice() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>PUBLIC.ORDERED_PRODUCTS.ORDERED_PRICE</code>.
     */
    public void setOrderedPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UUID, UUID, BigDecimal> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UUID, UUID, BigDecimal> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return OrderedProducts.ORDERED_PRODUCTS.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return OrderedProducts.ORDERED_PRODUCTS.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return OrderedProducts.ORDERED_PRODUCTS.ORDERED_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getOrderedPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getOrderedPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderedProductsRecord value1(UUID value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderedProductsRecord value2(UUID value) {
        setProductId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderedProductsRecord value3(BigDecimal value) {
        setOrderedPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderedProductsRecord values(UUID value1, UUID value2, BigDecimal value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
