/*
 * This file is generated by jOOQ.
 */
package com.avasiliuk.testtask.model.jooq;


import com.avasiliuk.testtask.model.jooq.tables.OrderedProducts;
import com.avasiliuk.testtask.model.jooq.tables.Orders;
import com.avasiliuk.testtask.model.jooq.tables.Products;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FK_ORDERS_ID_INDEX_2 = Indexes0.FK_ORDERS_ID_INDEX_2;
    public static final Index FK_PRODUCTS_ID_INDEX_2 = Indexes0.FK_PRODUCTS_ID_INDEX_2;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index INDEX_ORDERS_CREATED = Indexes0.INDEX_ORDERS_CREATED;
    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;
    public static final Index PRIMARY_KEY_F = Indexes0.PRIMARY_KEY_F;
    public static final Index UNIQUE_PRODUCTS_NAME = Indexes0.UNIQUE_PRODUCTS_NAME;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FK_ORDERS_ID_INDEX_2 = Internal.createIndex("FK_ORDERS_ID_INDEX_2", OrderedProducts.ORDERED_PRODUCTS, new OrderField[]{OrderedProducts.ORDERED_PRODUCTS.ORDER_ID}, false);
        public static Index FK_PRODUCTS_ID_INDEX_2 = Internal.createIndex("FK_PRODUCTS_ID_INDEX_2", OrderedProducts.ORDERED_PRODUCTS, new OrderField[]{OrderedProducts.ORDERED_PRODUCTS.PRODUCT_ID}, false);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", OrderedProducts.ORDERED_PRODUCTS, new OrderField[]{OrderedProducts.ORDERED_PRODUCTS.ORDER_ID, OrderedProducts.ORDERED_PRODUCTS.PRODUCT_ID}, true);
        public static Index INDEX_ORDERS_CREATED = Internal.createIndex("INDEX_ORDERS_CREATED", Orders.ORDERS, new OrderField[]{Orders.ORDERS.CREATED}, false);
        public static Index PRIMARY_KEY_8 = Internal.createIndex("PRIMARY_KEY_8", Orders.ORDERS, new OrderField[]{Orders.ORDERS.ID}, true);
        public static Index PRIMARY_KEY_F = Internal.createIndex("PRIMARY_KEY_F", Products.PRODUCTS, new OrderField[]{Products.PRODUCTS.ID}, true);
        public static Index UNIQUE_PRODUCTS_NAME = Internal.createIndex("UNIQUE_PRODUCTS_NAME", Products.PRODUCTS, new OrderField[]{Products.PRODUCTS.NAME}, true);
    }
}
