/*
 * This file is generated by jOOQ.
 */
package com.avasiliuk.testtask.model.jooq;


import com.avasiliuk.testtask.model.jooq.tables.OrderedProducts;
import com.avasiliuk.testtask.model.jooq.tables.Orders;
import com.avasiliuk.testtask.model.jooq.tables.Products;
import com.avasiliuk.testtask.model.jooq.tables.records.OrderedProductsRecord;
import com.avasiliuk.testtask.model.jooq.tables.records.OrdersRecord;
import com.avasiliuk.testtask.model.jooq.tables.records.ProductsRecord;
import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>PUBLIC</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OrderedProductsRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<OrdersRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<ProductsRecord> CONSTRAINT_F = UniqueKeys0.CONSTRAINT_F;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<OrderedProductsRecord, OrdersRecord> FK_ORDERS_ID = ForeignKeys0.FK_ORDERS_ID;
    public static final ForeignKey<OrderedProductsRecord, ProductsRecord> FK_PRODUCTS_ID = ForeignKeys0.FK_PRODUCTS_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<OrderedProductsRecord> CONSTRAINT_2 = Internal.createUniqueKey(OrderedProducts.ORDERED_PRODUCTS, "CONSTRAINT_2", OrderedProducts.ORDERED_PRODUCTS.ORDER_ID, OrderedProducts.ORDERED_PRODUCTS.PRODUCT_ID);
        public static final UniqueKey<OrdersRecord> CONSTRAINT_8 = Internal.createUniqueKey(Orders.ORDERS, "CONSTRAINT_8", Orders.ORDERS.ID);
        public static final UniqueKey<ProductsRecord> CONSTRAINT_F = Internal.createUniqueKey(Products.PRODUCTS, "CONSTRAINT_F", Products.PRODUCTS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<OrderedProductsRecord, OrdersRecord> FK_ORDERS_ID = Internal.createForeignKey(com.avasiliuk.testtask.model.jooq.Keys.CONSTRAINT_8, OrderedProducts.ORDERED_PRODUCTS, "FK_ORDERS_ID", OrderedProducts.ORDERED_PRODUCTS.ORDER_ID);
        public static final ForeignKey<OrderedProductsRecord, ProductsRecord> FK_PRODUCTS_ID = Internal.createForeignKey(com.avasiliuk.testtask.model.jooq.Keys.CONSTRAINT_F, OrderedProducts.ORDERED_PRODUCTS, "FK_PRODUCTS_ID", OrderedProducts.ORDERED_PRODUCTS.PRODUCT_ID);
    }
}
