/*
 * This file is generated by jOOQ.
 */
package com.avasiliuk.testtask.model.jooq;


import com.avasiliuk.testtask.model.jooq.tables.OrderedProducts;
import com.avasiliuk.testtask.model.jooq.tables.Orders;
import com.avasiliuk.testtask.model.jooq.tables.Products;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();
    private static final long serialVersionUID = 1061287081;
    /**
     * The table <code>PUBLIC.ORDERED_PRODUCTS</code>.
     */
    public final OrderedProducts ORDERED_PRODUCTS = com.avasiliuk.testtask.model.jooq.tables.OrderedProducts.ORDERED_PRODUCTS;

    /**
     * The table <code>PUBLIC.ORDERS</code>.
     */
    public final Orders ORDERS = com.avasiliuk.testtask.model.jooq.tables.Orders.ORDERS;

    /**
     * The table <code>PUBLIC.PRODUCTS</code>.
     */
    public final Products PRODUCTS = com.avasiliuk.testtask.model.jooq.tables.Products.PRODUCTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                OrderedProducts.ORDERED_PRODUCTS,
                Orders.ORDERS,
                Products.PRODUCTS);
    }
}
