/*
 * This file is generated by jOOQ.
 */
package com.avasiliuk.testtask.model.jooq;


import com.avasiliuk.testtask.model.jooq.tables.OrderedProducts;
import com.avasiliuk.testtask.model.jooq.tables.Orders;
import com.avasiliuk.testtask.model.jooq.tables.Products;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>PUBLIC.ORDERED_PRODUCTS</code>.
     */
    public static final OrderedProducts ORDERED_PRODUCTS = com.avasiliuk.testtask.model.jooq.tables.OrderedProducts.ORDERED_PRODUCTS;

    /**
     * The table <code>PUBLIC.ORDERS</code>.
     */
    public static final Orders ORDERS = com.avasiliuk.testtask.model.jooq.tables.Orders.ORDERS;

    /**
     * The table <code>PUBLIC.PRODUCTS</code>.
     */
    public static final Products PRODUCTS = com.avasiliuk.testtask.model.jooq.tables.Products.PRODUCTS;
}
